import type {
  ApplicationTask,
  AppSettings,
  Job,
  PipelineRun,
  ResumeProjectCatalogItem,
  StageEvent,
} from "../types";

export const createJob = (overrides: Partial<Job> = {}): Job => ({
  id: "job-1",
  source: "linkedin",
  sourceJobId: null,
  jobUrlDirect: null,
  datePosted: null,
  datePostedCheckedAt: null,
  title: "Backend Engineer",
  employer: "Acme Labs",
  employerUrl: null,
  jobUrl: "https://example.com/job-1",
  applicationLink: "https://example.com/apply",
  disciplines: null,
  deadline: null,
  salary: null,
  location: "California",
  degreeRequired: null,
  starting: null,
  jobDescription: "Job description content",
  status: "ready",
  outcome: null,
  closedAt: null,
  suitabilityScore: 90,
  suitabilityReason: "Strong fit",
  suitabilityReasonSource: null,
  semanticScore: null,
  keywordCoverage: null,
  keywordMissing: null,
  jobEmbedding: null,
  jobEmbeddingModel: null,
  jobEmbeddingHash: null,
  tailoredSummary: null,
  tailoredHeadline: null,
  tailoredSkills: null,
  selectedProjectIds: null,
  pdfPath: null,
  jobType: null,
  salarySource: null,
  salaryInterval: null,
  salaryMinAmount: null,
  salaryMaxAmount: null,
  salaryCurrency: null,
  isRemote: null,
  jobLevel: null,
  jobLevelCategory: null,
  jobFunction: null,
  listingType: null,
  emails: null,
  companyIndustry: null,
  companyLogo: null,
  companyUrlDirect: null,
  companyAddresses: null,
  companyNumEmployees: null,
  companyRevenue: null,
  companyDescription: null,
  skills: null,
  experienceRange: null,
  companyRating: null,
  companyReviewsCount: null,
  vacancyCount: null,
  workFromHomeType: null,
  discoveredAt: "2025-01-01T00:00:00Z",
  processedAt: null,
  appliedAt: null,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-01T00:00:00Z",
  ...overrides,
});

export const createStageEvent = (
  overrides: Partial<StageEvent> = {},
): StageEvent => ({
  id: "event-1",
  applicationId: "job-1",
  title: "Moved to applied",
  groupId: null,
  fromStage: null,
  toStage: "applied",
  occurredAt: Date.now(),
  metadata: null,
  outcome: null,
  ...overrides,
});

export const createApplicationTask = (
  overrides: Partial<ApplicationTask> = {},
): ApplicationTask => ({
  id: "task-1",
  applicationId: "job-1",
  type: "todo",
  title: "Follow up",
  dueDate: null,
  isCompleted: false,
  notes: null,
  ...overrides,
});

export const createPipelineRun = (
  overrides: Partial<PipelineRun> = {},
): PipelineRun => ({
  id: "run-1",
  startedAt: "2025-01-01T00:00:00Z",
  completedAt: null,
  status: "running",
  jobsDiscovered: 0,
  jobsProcessed: 0,
  errorMessage: null,
  ...overrides,
});

export const createResumeProjectCatalogItem = (
  overrides: Partial<ResumeProjectCatalogItem> = {},
): ResumeProjectCatalogItem => ({
  id: "p1",
  name: "Project 1",
  description: "Description 1",
  date: "2024",
  isVisibleInBase: true,
  ...overrides,
});

export const createAppSettings = (
  overrides: Partial<AppSettings> = {},
): AppSettings => ({
  model: { value: "gpt-4o", default: "gpt-4o", override: null },
  modelScorer: { value: "gpt-4o", override: null },
  modelTailoring: { value: "gpt-4o", override: null },
  modelProjectSelection: { value: "gpt-4o", override: null },
  companyModelRules: { value: [], default: [], override: null },
  llmProvider: { value: "openai", default: "openai", override: null },
  llmBaseUrl: {
    value: "https://api.openai.com/v1",
    default: "https://api.openai.com/v1",
    override: null,
  },
  pipelineWebhookUrl: { value: "", default: "", override: null },
  jobCompleteWebhookUrl: { value: "", default: "", override: null },
  whatsappEnabled: { value: false, default: false, override: null },
  whatsappPhone: { value: "", default: "", override: null },
  profileProjects: [],
  resumeProjects: {
    value: { maxProjects: 3, lockedProjectIds: [], aiSelectableProjectIds: [] },
    default: {
      maxProjects: 3,
      lockedProjectIds: [],
      aiSelectableProjectIds: [],
    },
    override: null,
  },
  adzunaMaxJobsPerTerm: { value: 50, default: 50, override: null },
  searchTerms: {
    value: ["Software Engineer"],
    default: ["Software Engineer"],
    override: null,
  },
  blockedCompanyKeywords: {
    value: [],
    default: [],
    override: null,
  },
  scoringInstructions: {
    value: "",
    default: "",
    override: null,
  },
  searchCities: {
    value: "United Kingdom",
    default: "United Kingdom",
    override: null,
  },
  jobspyResultsWanted: { value: 20, default: 20, override: null },
  jobspyCountryIndeed: {
    value: "united kingdom",
    default: "united kingdom",
    override: null,
  },
  chatStyleTone: {
    value: "professional",
    default: "professional",
    override: null,
  },
  chatStyleFormality: { value: "medium", default: "medium", override: null },
  chatStyleConstraints: { value: "", default: "", override: null },
  chatStyleDoNotUse: { value: "", default: "", override: null },
  chatStyleLanguageMode: {
    value: "manual",
    default: "manual",
    override: null,
  },
  chatStyleManualLanguage: {
    value: "english",
    default: "english",
    override: null,
  },
  llmApiKeyHint: null,
  embeddingApiKeyHint: null,
  basicAuthUser: null,
  embeddingProvider: null,
  embeddingBaseUrl: null,
  basicAuthPasswordHint: null,
  adzunaAppId: null,
  adzunaAppKeyHint: null,
  webhookSecretHint: null,
  whatsappApiKeyHint: null,
  basicAuthActive: false,
  backupEnabled: { value: false, default: false, override: null },
  backupHour: { value: 3, default: 3, override: null },
  backupMaxCount: { value: 7, default: 7, override: null },
  penalizeMissingSalary: { value: false, default: false, override: null },
  missingSalaryPenalty: { value: 10, default: 10, override: null },
  autoSkipScoreThreshold: { value: null, default: null, override: null },
  semanticScoreWeight: { value: 0.7, default: 0.7, override: null },
  embeddingEnabled: { value: false, default: false, override: null },
  embeddingMaxJobsPerRun: { value: 20, default: 20, override: null },
  embeddingMaxInputChars: { value: 6000, default: 6000, override: null },
  embeddingModel: {
    value: "text-embedding-3-small",
    default: "text-embedding-3-small",
    override: null,
  },
  ...overrides,
});
